import Link from 'next/link';
import type { Prisma } from '@prisma/client';

import { BackendError, get } from '@/lib/backend';
import { BackendDown } from '@/components/backend-down';
import { currentUser } from '@/lib/auth';
import { can } from '@/lib/domain';
import { timeAgo, fmtDateTime } from '@/lib/format';
import { paging, pageCount } from '@/lib/queries';
import {
  Badge,
  Card,
  Grid,
  GapNote,
  PageHeader,
  Stat,
  Table,
  EmptyRow,
} from '@/components/ui';
import { RowLink } from '@/components/ui/row-link';
import { FilterSelect, Pager } from '@/components/ui/client';
import { Composer } from './composer';
import { requirePage } from '@/lib/guard';

export const metadata = { title: 'Notifications · RannaBari Admin' };
export const dynamic = 'force-dynamic';

type NoteRow = {
  id: string;
  key: string;
  audience: string;
  kind: string;
  title: string;
  body: string;
  customerKey: string | null;
  kitchenId: string | null;
  zone: string | null;
  broadcastBy: string | null;
  read: boolean;
  at: string;
};

type Facets = {
  kinds: string[];
  unreadCustomer: number;
  unreadCook: number;
  zones: string[];
};

export default async function NotificationsPage({
  searchParams,
}: {
  searchParams: Promise<Record<string, string | undefined>>;
}) {
  await requirePage('order.read');
  const params = await searchParams;
  const { page, skip, take } = paging(params);
  const user = await currentUser();
  const canSend = can(user?.role ?? '', 'notification.broadcast');

  const where: Prisma.NotificationWhereInput = {};
  if (params.audience) where.audience = params.audience;
  if (params.kind) where.kind = params.kind;

  const query = new URLSearchParams({ skip: String(skip), take: String(take) });
  if (params.audience) query.set('audience', params.audience);
  if (params.kind) query.set('kind', params.kind);

  let rows: NoteRow[];
  let total: number;
  let facets: Facets;
  try {
    const data = await get<{ notifications: NoteRow[]; total: number; facets: Facets }>(
      `/notifications?${query}`,
    );
    rows = data.notifications;
    total = data.total;
    facets = data.facets;
  } catch (error) {
    if (error instanceof BackendError && error.status === 0) {
      return (
        <BackendDown
          title="Notifications"
          subtitle="What the platform has told people, and a way to tell them something"
        />
      );
    }
    throw error;
  }

  const { unreadCustomer, unreadCook } = facets;
  /* Kept in the row shapes the dropdowns already map over. */
  const kinds = facets.kinds.map((kind) => ({ kind }));
  const zones = facets.zones.map((name) => ({ name }));

  return (
    <>
      <PageHeader
        title="Notifications"
        subtitle="What the platform has told people, and a way to tell them something"
      />

      <GapNote>
        <strong>Why this screen exists.</strong> Every notification in the app is
        generated by the client, on the device, in response to something that device
        did. There is no way for the platform to say anything — not a delivery delay,
        not a festival menu, not an apology. The dedupe contract is the
        app&rsquo;s: a notification whose key is already sitting unread does not
        produce a second row, so a re-worded message cannot slip past it.
      </GapNote>

      <Grid cols={3}>
        <Stat label="Notifications on file" value={total} />
        <Stat label="Unread by customers" value={unreadCustomer} tone="info" />
        <Stat label="Unread by cooks" value={unreadCook} tone="info" />
      </Grid>

      <div className="mt-3 grid grid-cols-1 gap-3 lg:grid-cols-[1fr_1.6fr]">
        <Card title="Compose a broadcast">
          {canSend ? (
            <Composer zones={zones.map((z) => z.name)} />
          ) : (
            <p className="text-[13px] leading-relaxed text-ink3">
              Broadcasting needs the operations role. Sign in as ops@rannabari.app or
              admin@rannabari.app.
            </p>
          )}
        </Card>

        <Card
          pad={false}
          title="Sent"
          actions={
            <div className="flex flex-wrap gap-2">
              <FilterSelect
                name="audience"
                allLabel="Both audiences"
                options={[
                  { value: 'customer', label: 'Customers' },
                  { value: 'cook', label: 'Cooks' },
                ]}
              />
              <FilterSelect
                name="kind"
                allLabel="All kinds"
                options={kinds.map((k) => ({ value: k.kind, label: k.kind }))}
              />
            </div>
          }
        >
          <Table head={['Audience', 'Kind', 'Title', 'Read', 'From', 'When']}>
            {rows.map((note) => (
              <RowLink key={note.id} href={`/notifications/${note.id}`}>
                <td>
                  <Badge tone={note.audience === 'cook' ? 'warn' : 'info'}>
                    {note.audience}
                  </Badge>
                </td>
                <td className="text-ink2">{note.kind}</td>
                <td className="max-w-[260px]">
                  <Link href={`/notifications/${note.id}`} className="hover:text-primary">
                    <span className="block truncate font-medium">{note.title}</span>
                  </Link>
                  <span className="block truncate text-[11.5px] text-ink3">{note.body}</span>
                </td>
                <td>
                  {note.read ? <Badge tone="good">read</Badge> : <Badge>unread</Badge>}
                </td>
                <td className="max-w-[140px] truncate text-[11.5px] text-ink3">
                  {note.broadcastBy ?? 'app'}
                </td>
                <td className="whitespace-nowrap text-ink2" title={fmtDateTime(note.at)}>
                  {timeAgo(note.at)}
                </td>
              </RowLink>
            ))}
            {rows.length === 0 ? <EmptyRow span={6}>Nothing matches that.</EmptyRow> : null}
          </Table>

          <Pager page={page} pages={pageCount(total)} total={total} />
        </Card>
      </div>
    </>
  );
}
